# Generated by Django 2.2.5 on 2019-10-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_key', models.CharField(max_length=64, unique=True)),
                ('sensor_name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMeasurementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('specific_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_measurements.SensorModel')),
            ],
        ),
    ]
